### ISSUE TITLE
Plugin ID mismatch error

### ISSUE THREAD

**Issue by ngirard** [dellermann/obsidian-console#1]
Hey Daniel,

Using Obsidian v1.1.12 on Ubuntu 22.04, I wanted to give your plugin a try, but the installation failed with such "Plugin ID mismatch" error.

Cheers, and thanks for your work !

**Comment by swehba** [comment]
+1

**Comment by dellermann** [comment]
This has been fixed in version 1.0.2 of the plugin.

**Comment by ngirard** [comment]
Great, thanks !
