### ISSUE TITLE
Provide more details in the Readme

### ISSUE THREAD

**Issue by profucius** [dellermann/obsidian-console#2]
There are some details which I think need to be added to the Readme for your plugin.

1. Which operation system(s) is this designed for?
2. Some use-cases/purposes for this plugin.
3. Ability and restrictions of this plugin.

Curious to know more. Thanks

**Comment by dellermann** [comment]
It's for all platforms where Obsidian is available. Use cases are already shown in the README. There are no restrictions.

Please don't request for more work than really needed!

**Comment by profucius** [comment]
It's called documentation, but if you're not interested in including enough to support the use of your plugin, then I don't see the need to attempt to use it.
